// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv_crn26Vy32Awi95qu08twfx99PkaQAM',
    appId: '1:542530489821:web:45e60f3692aae868f4ba34',
    messagingSenderId: '542530489821',
    projectId: 'mashappbuild-a7068',
    authDomain: 'mashappbuild-a7068.firebaseapp.com',
    storageBucket: 'mashappbuild-a7068.firebasestorage.app',
    measurementId: 'G-XP60TMMYJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAurHVXuhSuHpR93ncJQcKxSlYvWO-hpJA',
    appId: '1:542530489821:android:eb2212c619130837f4ba34',
    messagingSenderId: '542530489821',
    projectId: 'mashappbuild-a7068',
    storageBucket: 'mashappbuild-a7068.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuoaBFKm_tsmxLrcIRBaSFplty6ud1qOo',
    appId: '1:542530489821:ios:96b576ee636b3627f4ba34',
    messagingSenderId: '542530489821',
    projectId: 'mashappbuild-a7068',
    storageBucket: 'mashappbuild-a7068.firebasestorage.app',
    iosBundleId: 'com.example.mashGrowerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuoaBFKm_tsmxLrcIRBaSFplty6ud1qOo',
    appId: '1:542530489821:ios:96b576ee636b3627f4ba34',
    messagingSenderId: '542530489821',
    projectId: 'mashappbuild-a7068',
    storageBucket: 'mashappbuild-a7068.firebasestorage.app',
    iosBundleId: 'com.example.mashGrowerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv_crn26Vy32Awi95qu08twfx99PkaQAM',
    appId: '1:542530489821:web:15ef157b8232d78bf4ba34',
    messagingSenderId: '542530489821',
    projectId: 'mashappbuild-a7068',
    authDomain: 'mashappbuild-a7068.firebaseapp.com',
    storageBucket: 'mashappbuild-a7068.firebasestorage.app',
    measurementId: 'G-PQ9CFPJH7M',
  );

}