// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQryxFIjEjXApWMZP2H2ZkHIlWxUMuVO0',
    appId: '1:1001664140460:web:b4b2f9fe91dc55873cfb09',
    messagingSenderId: '1001664140460',
    projectId: 'mash-5b627',
    authDomain: 'mash-5b627.firebaseapp.com',
    storageBucket: 'mash-5b627.firebasestorage.app',
    measurementId: 'G-JW9J55J60Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQryxFIjEjXApWMZP2H2ZkHIlWxUMuVO0',
    appId: '1:1001664140460:android:REGISTER_IN_FIREBASE_CONSOLE',
    messagingSenderId: '1001664140460',
    projectId: 'mash-5b627',
    storageBucket: 'mash-5b627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQryxFIjEjXApWMZP2H2ZkHIlWxUMuVO0',
    appId: '1:1001664140460:ios:REGISTER_IN_FIREBASE_CONSOLE',
    messagingSenderId: '1001664140460',
    projectId: 'mash-5b627',
    storageBucket: 'mash-5b627.firebasestorage.app',
    iosBundleId: 'com.example.mashGrowerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQryxFIjEjXApWMZP2H2ZkHIlWxUMuVO0',
    appId: '1:1001664140460:ios:REGISTER_IN_FIREBASE_CONSOLE',
    messagingSenderId: '1001664140460',
    projectId: 'mash-5b627',
    storageBucket: 'mash-5b627.firebasestorage.app',
    iosBundleId: 'com.example.mashGrowerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQryxFIjEjXApWMZP2H2ZkHIlWxUMuVO0',
    appId: '1:1001664140460:web:b4b2f9fe91dc55873cfb09',
    messagingSenderId: '1001664140460',
    projectId: 'mash-5b627',
    authDomain: 'mash-5b627.firebaseapp.com',
    storageBucket: 'mash-5b627.firebasestorage.app',
    measurementId: 'G-JW9J55J60Q',
  );

}